AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cloud Resume Challenge - Backend (Visitor Counter)

Globals:
  Function:
    Timeout: 5
    Runtime: python3.13
    MemorySize: 128

Resources:

  VisitorTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VisitorCount
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  PythonVisitorCount:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: VisitorCounterFunction
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VisitorTable
      Environment:
        Variables:
          TABLE_NAME: !Ref VisitorTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /count
            Method: get

Outputs:
  ApiUrl:
    Description: API base invoke URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  CountEndpoint:
    Description: Full /count endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/count"
